### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by corybrunson** [TomKellyGenetics/graphsim#10]
The README does not indicate how users might contribute to the package, nor is there a CONTRIBUTING file. The latter is preferable, and there are several points of reference, for example [this contributing template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) and the [ggplot2 contributing guidelines](https://github.com/tidyverse/ggplot2/blob/master/CONTRIBUTING.md) (from which i adapted my own for a ggplot2 extension). You may of course want to tailor it to the specific design, use, needs, etc. of your package!

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2161)._

**Comment by TomKellyGenetics** [comment]
I've added [contributing guidelines](https://github.com/TomKellyGenetics/graphsim/blob/master/CONTRIBUTING.md), an [issue template](https://github.com/TomKellyGenetics/graphsim/blob/master/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md), and a [code of conduct](https://github.com/TomKellyGenetics/graphsim/blob/master/CODE_OF_CONDUCT.md). This follows the examples given for [ggplot2](https://github.com/igraph/rigraph/blob/dev/CONTRIBUTING.md) and [r-igraph](https://github.com/tidyverse/ggplot2/blob/master/CONTRIBUTING.md) and aims at contributors who may not be familiar with GitHub. I've also added the URL for the GitHub repo to the DESCRIPTION so it can be found from the CRAN release.

**Comment by corybrunson** [comment]
This looks good! I'd only suggest that you adapt the issue template to reflect the GitHub setting and any particular preferences for your repo.

**Comment by TomKellyGenetics** [comment]
GitHub the Issue Template with this notice. I'll review this and see if I can update it to be compatible the [new version](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) of GitHub templates.

![Screen Shot 2020-04-22 at 19 15 14](https://user-images.githubusercontent.com/5493325/79970304-ad5df700-84cd-11ea-86e3-d62d481a2d74.png)

**Comment by TomKellyGenetics** [comment]
Using GitHub "Setting" to [configure](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) the new issue format seems to have it up properly. I don't have strong preferences on how issues are submitted. I've removed anything specific to the tidyverse and I think it's sorted now.

![Screen Shot 2020-04-30 at 17 20 05](https://user-images.githubusercontent.com/5493325/80688633-144f6180-8b07-11ea-991a-b62f828cf154.png)
