### ISSUE TITLE
[JOSS Review] 

### ISSUE THREAD

**Issue by rcannood** [TomKellyGenetics/graphsim#13]
Sorry for the delay in my review. Below are several concerns regarding the article and the documentation (related to openjournals/joss-reviews#2161). 

- [x] **Refine [introduction](https://github.com/TomKellyGenetics/graphsim#simulate-expression-data-from-igraph-networks) in README**: Better highlight the statement of need. In the article this was clearly stated in the first paragraph. In the readme, not so much.
- [x] **[Installation instructions](https://github.com/TomKellyGenetics/graphsim#installation)**: There's no need to manually install the dependency packages; `install.packages("graphsim")` will install the dependencies for you.
- [x] **Documentation**: Some of the vignettes (e.g. test_graph_divergent.Rmd) do not contain enough documentation / description of the plots being produced to understand what is going on.
- [x] **State of the field**: Please compare against similar methods, including [dyngen](https://www.biorxiv.org/content/10.1101/2020.02.06.936971v2), [SERGIO](https://www.biorxiv.org/content/10.1101/716811v1.abstract), [GeneNetWeaver](https://www.ncbi.nlm.nih.gov/pubmed/21697125).
- [x] **Code in manuscript**: Remove installation instructions or move it to a separate section. Since graphsim is on cran, the installation instructions can just be `install.packages("graphsim")`. You don't need to install devtools or igraph.
- [x] **Code in manuscript**: Fix syntax highlighting issue at the bottom of page 6 due to `trace = "none\",`.
- [x] **Code in manuscript**: Given that there is a one-to-one relation between the figures generated and the code blocks, would it be desirable to use an Rmd instead of an md file? This part is up for discussion. Example of Rmd JOSS paper: https://github.com/tidyverse/tidyverse/blob/master/vignettes/paper.Rmd

**Comment by TomKellyGenetics** [comment]
Thanks for the review, sorry for taking a while to get back on this. I'll start making corrections to address these.

As also mentioned by @corybrunson [here](https://github.com/openjournals/joss-reviews/issues/2161#issuecomment-601921101) there is an issue reproducing the inhibition plots. I've made some adjustments to the package so that hardcoded variables are not required for this. This is the first step to make sure the code is reproducible. I'll update paper.md consider switching to Rmarkdown format. Figure 3 will need to be updated to account for these changes.



Here is a preview of the code for the first 3 figures. This runs in the [current version](935cf6a]) pushed to master. 

```
######## Section 1 ####################

#install packages required (once per machine)
install.packages("graphsim")

#load required packages (once per R instance)
library("igraph")
library("graphsim")
library("gplots")
#generate graph structure
graph_edges <- rbind(c("A", "C"), c("B", "C"), c("C", "D"), c("D", "E"),
                     c("D", "F"), c("F", "G"), c("F", "I"), c("H", "I"))
graph <- graph.edgelist(graph_edges, directed = TRUE)
#plot graph structure (Figure 1)
plot_directed(graph, state ="activating", layout = layout.kamada.kawai,
              cex.node=3, cex.arrow=5, arrow_clip = 0.2)
#generate parameters for inhibitions
state <- c(1, 1, -1, 1, 1, 1, 1, -1, 1)
#plot graph structure with inhibitions (Figure 2)
plot_directed(graph, state=state, layout = layout.kamada.kawai,
              cex.node=3, cex.arrow=5, arrow_clip = 0.2)

######## Section 2 ####################

# activating graph
state <- rep(length(E(graph)), 1)
plot_directed(graph, state=state, layout = layout.kamada.kawai,
              cex.node=3, cex.arrow=5, arrow_clip = 0.2)

#adjacency matrix
adj_mat <- make_adjmatrix_graph(graph)
#relationship matrix
dist_mat <- make_distance_graph(graph, absolute = FALSE)
#sigma matrix directly from graph
sigma_mat <- make_sigma_mat_dist_graph(graph, 0.8, absolute = FALSE)
#show shortest paths of graph
shortest_paths <- shortest.paths(graph)
#generate expression data directly from graph
expr <- generate_expression(100, graph, cor = 0.8, mean = 0, comm = FALSE,
                            dist = TRUE, absolute = FALSE, state = state)
#plot adjacency matrix
heatmap.2(make_adjmatrix_graph(graph), scale = "none", trace = "none",
          col = colorpanel(3, "grey75", "white", "blue"),
          colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
#plot relationship matrix
heatmap.2(make_distance_graph(graph, absolute = FALSE),
          scale = "none", trace = "none", col = colorpanel(50, "white", "red"),
colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
#plot sigma matrix
heatmap.2(make_sigma_mat_dist_graph(graph, 0.8, absolute = FALSE),
scale = "none", trace = "none", col = colorpanel(50, "white", "red"),
colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
expr <- generate_expression(100, graph, cor = 0.8, mean = 0,
comm = FALSE, dist =TRUE, absolute = FALSE, state = state)
#plot simulated expression data
heatmap.2(expr, scale = "none", trace = "none", col = bluered(50),
colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
#plot simulated correlations
heatmap.2(cor(t(expr)), scale = "none", trace = "none", col = colorpanel(50, "white", "red"),
colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))


######## Section 3 ####################

#generate parameters for inhibitions
state <- c(1, 1, -1, 1, 1, 1, 1, -1, 1)
plot_directed(graph, state=state, layout = layout.kamada.kawai,
              cex.node=3, cex.arrow=5, arrow_clip = 0.2)

#adjacency matrix
adj_mat <- make_adjmatrix_graph(graph)
#relationship matrix
dist_mat <- make_distance_graph(graph, absolute = FALSE)
#state matrix
state_mat <- make_state_matrix(graph, state)
#sigma matrix directly from graph
sigma_mat <- make_sigma_mat_dist_graph(graph, state = state, 0.8, absolute = FALSE)
#show shortest paths of graph
shortest_paths <- shortest.paths(graph)
#generate expression data directly from graph
expr <- generate_expression(100, graph, cor = 0.8, mean = 0, comm = FALSE,
                            dist = TRUE, absolute = FALSE, state = state)
#plot adjacency matrix
heatmap.2(make_adjmatrix_graph(graph), scale = "none", trace = "none",
          col = colorpanel(3, "grey75", "white", "blue"),
          colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
#plot state matrix
heatmap.2(make_state_matrix(graph, state),
          scale = "none", trace = "none", col = colorpanel(50, "white", "red"),
          colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
#plot relationship matrix
heatmap.2(make_distance_graph(graph, absolute = FALSE),
          scale = "none", trace = "none", col = colorpanel(50, "white", "red"),
          colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
#plot sigma matrix
heatmap.2(make_sigma_mat_dist_graph(graph, state = state, 0.8, absolute = FALSE),
          scale = "none", trace = "none", col = colorpanel(50, "blue", "white", "red"),
          colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
expr <- generate_expression(100, graph, state = state, cor = 0.8, mean = 0,
                            comm = FALSE, dist =TRUE, absolute = FALSE)
#plot simulated expression data
heatmap.2(expr, scale = "none", trace = "none", col = bluered(50),
          colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
#plot simulated correlations
heatmap.2(cor(t(expr)), scale = "none", trace = "none", col = colorpanel(50, "blue", "white", "red"),
          colsep = 1:length(V(graph)), rowsep = 1:length(V(graph)))
```

I think these results better represent the input graph. Various updates to [`make_state_matrix`](https://github.com/TomKellyGenetics/graphsim/blob/master/R/state.R) allow for disconnected graphs and cycles. Ideally the input graph is a directed acyclic tree but  a Sigma matrix can be generated if the graph object is not so clean and tidy (as happens in biology).

## Figure 3
### Inhibiting graph structure
![Rplot](https://user-images.githubusercontent.com/5493325/80210044-05336400-866e-11ea-8ff1-aefcc480e844.png)
### Sigma
![sigma](https://user-images.githubusercontent.com/5493325/80209600-5131d900-866d-11ea-9666-72ae963c37c6.png)
### Correlations
![cor](https://user-images.githubusercontent.com/5493325/80209583-4e36e880-866d-11ea-826c-9ce3d24534ad.png)
### Simulated Expression
![expr](https://user-images.githubusercontent.com/5493325/80209597-50994280-866d-11ea-8f0a-dd1a5cd9f6a9.png)

This is a work in progress. I'll update the unit tests and vignettes to reflect these changes before revising the manuscript.

**Comment by TomKellyGenetics** [comment]
Issue with trace is fixed with commit cbe48d326c0cd82fdc19.

**Comment by TomKellyGenetics** [comment]
>Code in manuscript: Given that there is a one-to-one relation between the figures generated and the code blocks, would it be desirable to use an Rmd instead of an md file?

An Rmarkdown version of the paper has been generated. I've made some alterations to the output to allow different sized figures. I've made these changes to the TeX file to generate a preview of the PDF and the same changes to the markdown for @whedon. Subcaptions for figure panes are generated in R graphics to avoid depending on TeX packages for whedon. The Rmarkdown is a bit complicated to do this but it seems to work. I use `set.seed` and `pdf` (sizes in inches at 75 dpi) calls in R to make sure the larger figure (2E, 3E, and 4E) are the same 'pseudo-random' data as the smaller figure it replaces.

Thanks for the suggestion. I'm quite happy with the Rmarkdown format so I'll use something similar for the vignettes (as raised here and #11). Once I've got the documentation sorted, I'll update the text of the manuscript.

**Comment by rcannood** [comment]
Cool! I like the changes you've made; it's much easier to see what code is used to produce which figure. 

One suggestion, in the "load required packages" session you might want to turn off messages (for example like this [6f979bb](https://github.com/rcannood/graphsim/commit/6f979bbb3513b95872b9e4227d7a30699e27fd14))). Perhaps you might also want to remove some of the warnings that are generated throughout the paper as well, but I'll leave that choice up to you. 

↓ Warning such as these are usually a sign that something is amiss.
```r
#> Warning in eattrs[[name]][index] <- value: number of items to
#> replace is not a multiple of replacement length
#> Warning in state_path[jj] <- state[kk]: number of items to replace
#> is not a multiple of replacement length
```

**Comment by TomKellyGenetics** [comment]
As suggested by the editors, removing some code examples from the paper would reduce the length. I like the Rmarkdown format though so I will keep it raw Rmd file to refer to reproduce the figures. I've also put similar examples in the [updated vignettes](https://github.com/TomKellyGenetics/graphsim/blob/66ba7f8e5e8e2f13784079338f44f9dc87eb58ff/vignettes/simulate_expression.Rmd). I hope this is acceptable to reduce the length of the paper while providing examples of the code. I've removed messages printed from the `library` calls as recommended.

>#> Warning in eattrs[[name]][index] <- value: number of items to
>#> replace is not a multiple of replacement length
>#> Warning in state_path[jj] <- state[kk]: number of items to replace
>#> is not a multiple of replacement length

I ran into this warning when computing the vignettes on empirical graphs from Reactome, it has been resolved [here](https://github.com/TomKellyGenetics/graphsim/blob/66ba7f8e5e8e2f13784079338f44f9dc87eb58ff/R/state.R#L164-L184). 

I'm still updating the paper and documentation but hopefully it won't take much longer to have a revised version ready.

**Comment by rcannood** [comment]
Good job @TomKellyGenetics +1 ! I went through the new versions of the article and the documentation on the graphsim GitHub repo. I'm pleased to see that the article is looking really nice. The changes you made adequately address my previous concerns. I will be ticking off the remaining boxes in openjournals/joss-reviews#2161.

**Comment by rcannood** [comment]
Good job @TomKellyGenetics :+1: ! I went through the new versions of the article and the documentation on the graphsim GitHub repo. I'm pleased to see that the article is looking really nice. The changes you made adequately address my previous concerns. I will be ticking off the remaining boxes in openjournals/joss-reviews#2161.

**Comment by TomKellyGenetics** [comment]
That's great to hear. Thanks for the quick response!
