### ISSUE TITLE
[JOSS Review] Update paper to reflect acceptance on CRAN

### ISSUE THREAD

**Issue by rcannood** [TomKellyGenetics/graphsim#5]
Since graphsim has been published on CRAN, update manuscript accordingly. For example, `devtools::install_github("TomKellyGenetics/graphsim")` should be replaced with `install.packages("graphsim")`.

**Comment by TomKellyGenetics** [comment]
Thanks for pointing this out. The manuscript has been changed to reflect this. Additionally references to `plot_directed` in the `plot.igraph` package have been removed as this function has been migrated into `graphsim` to avoid remote dependencies on CRAN.
