### ISSUE TITLE
igraph dependency

### ISSUE THREAD

**Issue by corybrunson** [TomKellyGenetics/graphsim#7]
Is graphsim meant to be used (a) always in tandem with igraph or (b) sometimes in a standalone way? The examples all load igraph, but many of them still work if the occasional igraph functions are accessed using `igraph::`. If the package is not meant to be used without also loading igraph, then perhaps it makes sense for igraph to be listed under Depends rather than Imports (in the DESCRIPTION); or, if the package is meant to be used, at least sometimes, on its own, then perhaps some examples could do without loading igraph? Maybe the current design is intentional, and my review won't hinge on this, but i thought it worth asking.

(Also, a formatting point: the igraph package is usually formatting in all-lowercase, rather than "iGraph", as sometimes appears in the documentation.)

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2161)._

**Comment by TomKellyGenetics** [comment]
Some functions running matrix operations should work without igraph loaded. The `library(igraph)` call in the examples is used for the `igraph` object class created by `graph_from_adjacency`. All igraph functions required by the functions in the package are imported but others are not.

I'm not sure whether listing igraph in "Depends" or "Imports" is better. Does this explanation help? If I understand correctly, we can remove the `library(igraph)` calls in the examples if the DESCRIPTION contains `Depends: igraph`.

**Comment by corybrunson** [comment]
Yes, that's true, since then loading graphsim would have the effect of loading igraph (and graphsim is automatically loaded before examples are run).

It sounds to me like the package is not intended as an extension of igraph, i.e. it is intended for at least some use cases that don't require additional igraph functionality. As such, it's appropriate to leave igraph under `Imports`.

**Comment by TomKellyGenetics** [comment]
Thanks for clarifying. In that case, I will leave `Imports: igraph` in the DESCRIPTION.

For examples in [documentation](https://github.com/TomKellyGenetics/graphsim/issues/6) and [vignettes](https://github.com/TomKellyGenetics/graphsim/issues/11) `library("igraph")` will still be needed to be called separately to use other `igraph` functions and the "igraph" object class.
