### ISSUE TITLE
cor default

### ISSUE THREAD

**Issue by corybrunson** [TomKellyGenetics/graphsim#8]
The `make_sigma` documentation says that the `cor` parameter defaults to 0.8, but currently there is no default:

``` r
library(igraph, warn.conflicts = FALSE)
library(graphsim)
graph_test_edges <- rbind(c("A", "B"), c("B", "C"), c("B", "D"))
graph_test <- graph.edgelist(graph_test_edges, directed = TRUE)
adjacency_matrix <- make_adjmatrix_graph(graph_test)
make_sigma_mat_adjmat(adjacency_matrix)
#> Error in ifelse(mat > 0, cor, 0): argument "cor" is missing, with no default
make_sigma_mat_adjmat(adjacency_matrix, cor = 0.8)
#>     A   B   C   D
#> A 1.0 0.8 0.0 0.0
#> B 0.8 1.0 0.8 0.8
#> C 0.0 0.8 1.0 0.0
#> D 0.0 0.8 0.0 1.0
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Either the behavior or the documentation should be changed. : )

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2161)._

**Comment by TomKellyGenetics** [comment]
Thanks for pointing this out. I've updated behaviour of the function to match the documentation and the `generate_expression` function which has the same parameter.

https://github.com/TomKellyGenetics/graphsim/blob/8dba70f20fc28360b157f58cb45ebe2db716b070/R/generate.R#L32

**Comment by corybrunson** [comment]
Seems to work! Thanks.
