### ISSUE TITLE
common link graph returned invisibly

### ISSUE THREAD

**Issue by corybrunson** [TomKellyGenetics/graphsim#9]
Is it intended for the common link graph computed by `make_commonlink_graph()` to be returned invisibly, whereas other functions use `return()` (which ensures that the returned object is printed)? I'm flagging it in case the different behavior was accidental.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/2161)._

**Comment by TomKellyGenetics** [comment]
Thanks, I wasn't aware that this resulted in different behaviour. The function has been updated for consistency.
